// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8XdNBe1jSLXmiczXIIsvAwvEjt7yUOrg',
    appId: '1:438967415379:web:245357f27f74447bb5cca6',
    messagingSenderId: '438967415379',
    projectId: 'notefire263',
    authDomain: 'notefire263.firebaseapp.com',
    storageBucket: 'notefire263.appspot.com',
    measurementId: 'G-LTQ27G9DTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCnEPTEIbElds8GNlL02Yc7H0nRWBqowQ',
    appId: '1:438967415379:android:7c450d1d4bbe5451b5cca6',
    messagingSenderId: '438967415379',
    projectId: 'notefire263',
    storageBucket: 'notefire263.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-RgQKk4F01zR7gw03oqfMBIHTP48bEfc',
    appId: '1:438967415379:ios:af5229b0fc58b551b5cca6',
    messagingSenderId: '438967415379',
    projectId: 'notefire263',
    storageBucket: 'notefire263.appspot.com',
    iosBundleId: 'com.example.notesFireApp263',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-RgQKk4F01zR7gw03oqfMBIHTP48bEfc',
    appId: '1:438967415379:ios:fd91c51ba82e46b4b5cca6',
    messagingSenderId: '438967415379',
    projectId: 'notefire263',
    storageBucket: 'notefire263.appspot.com',
    iosBundleId: 'com.example.notesFireApp263.RunnerTests',
  );
}
